version: "3"
services:
  postgres:
    image: postgres
    restart: "unless-stopped"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=some-password
      - POSTGRES_DB=qca
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web

  server:
    tty: true
    restart: "unless-stopped"
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - web

networks:
  web:
    external: true

